# Generated by Django 2.0.13 on 2019-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpellAreaOfEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'spell area of effect',
                'verbose_name_plural': 'spell areas of effect',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpellCastingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'spell casting time',
                'verbose_name_plural': 'spell casting times',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpellComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'spell component',
                'verbose_name_plural': 'spell components',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpellCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'spell cost',
                'verbose_name_plural': 'spell costs',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpellFlavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'spell flavour',
                'verbose_name_plural': 'spell flavours',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpellPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
                ('wounds', models.IntegerField(default=0, verbose_name='wounds')),
            ],
            options={
                'verbose_name': 'spell power',
                'verbose_name_plural': 'spell powers',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpellRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'spell range',
                'verbose_name_plural': 'spell ranges',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpellType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'spell type',
                'verbose_name_plural': 'spell types',
                'ordering': ('id',),
            },
        ),
    ]
