# Generated by Django 2.0.13 on 2019-04-29 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('area_of_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellAreaOfEffect')),
            ],
        ),
        migrations.CreateModel(
            name='SpellAreaOfEffectRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'spell area of effect range',
                'verbose_name_plural': 'spell areas of effect range',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='spell',
            name='area_of_effect_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellAreaOfEffectRange'),
        ),
        migrations.AddField(
            model_name='spell',
            name='casting_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellCastingTime'),
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellComponents'),
        ),
        migrations.AddField(
            model_name='spell',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellCost'),
        ),
        migrations.AddField(
            model_name='spell',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spell',
            name='flavour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellFlavour'),
        ),
        migrations.AddField(
            model_name='spell',
            name='power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellPower'),
        ),
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellRange'),
        ),
        migrations.AddField(
            model_name='spell',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellType'),
        ),
    ]
