# Generated by Django 2.0.13 on 2019-04-28 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0002_auto_20190429_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text_de', models.TextField(verbose_name='rule text')),
                ('rule_text_en', models.TextField(blank=True, null=True, verbose_name='rule text')),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellFlavour', verbose_name='flavour')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellPower', verbose_name='power')),
            ],
            options={
                'verbose_name': 'spell rule',
                'verbose_name_plural': 'spell rule',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='spell',
            name='area_of_effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellAreaOfEffect', verbose_name='area of effect'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='area_of_effect_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellAreaOfEffectRange', verbose_name='area of effect range'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellCastingTime', verbose_name='casting time'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellComponents', verbose_name='components'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellCost', verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='flavour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellFlavour', verbose_name='flavour'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellPower', verbose_name='power'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellRange', verbose_name='range'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.SpellType', verbose_name='type'),
        ),
    ]
