# Generated by Django 2.0.13 on 2019-06-17 15:23

from django.db import migrations


def copy_flavour_to_type(apps, schema_editor):
    SpellFlavour = apps.get_model('magic', 'SpellFlavour')
    SpellType = apps.get_model('magic', 'SpellType')

    SpellType.objects.all().delete()
    for sf in SpellFlavour.objects.all():
        SpellType.objects.create(
            name_de=sf.name_de,
            name_en=sf.name_en,
            cost=sf.cost
        )
    SpellFlavour.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0004_auto_20190428_2045'),
    ]

    operations = [
        migrations.RunPython(copy_flavour_to_type)
    ]
