# Generated by Django 3.2.5 on 2021-07-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0008_auto_20210724_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'spell source',
                'verbose_name_plural': 'spell sources',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='spelltype',
            name='cost',
        ),
        migrations.AddField(
            model_name='basespell',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magic.spellsource', verbose_name='source'),
            preserve_default=False,
        ),
    ]
