# Generated by Django 3.2.5 on 2021-07-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0009_auto_20210724_0832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpellSource',
            new_name='SpellVariant',
        ),
        migrations.AlterModelOptions(
            name='spellvariant',
            options={'ordering': ('id',), 'verbose_name': 'spell variant', 'verbose_name_plural': 'spell variants'},
        ),
        migrations.RemoveField(
            model_name='basespell',
            name='source',
        ),
        migrations.AddField(
            model_name='basespell',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magic.spellvariant', verbose_name='variant'),
            preserve_default=False,
        ),
    ]
