# Generated by Django 3.2.5 on 2021-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0010_auto_20210724_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basespell',
            options={'ordering': ('id',), 'verbose_name': 'base spell', 'verbose_name_plural': 'base spells'},
        ),
        migrations.AddField(
            model_name='basespell',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='cost'),
            preserve_default=False,
        ),
    ]
