# Generated by Django 3.2.5 on 2021-07-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0012_auto_20210726_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='spelltype',
            name='fa_icon_class',
            field=models.CharField(default='fas fa-book', max_length=30, verbose_name='FA Icon Class'),
        ),
        migrations.AddField(
            model_name='spelltype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='extension_images', verbose_name='image'),
        ),
    ]
