# Generated by Django 3.2.5 on 2021-08-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0015_spelltype_dominant_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basespell',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='spelltemplate',
            name='cost',
        ),
        migrations.AddField(
            model_name='basespell',
            name='spell_point_cost',
            field=models.IntegerField(default=1, verbose_name='spell point cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spelltemplate',
            name='spell_point_cost',
            field=models.IntegerField(default=1, verbose_name='spell point cost'),
        ),
    ]
