# Generated by Django 3.2.5 on 2021-08-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0016_auto_20210811_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='basespell',
            name='arcana_cost',
            field=models.IntegerField(default=1, verbose_name='arcana cost'),
        ),
    ]
