# Generated by Django 3.2.6 on 2021-08-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0017_basespell_arcana_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spelltemplatemodifier',
            name='attribute',
            field=models.CharField(blank=True, choices=[('power', 'power'), ('range', 'range'), ('actions', 'actions'), ('arcana_cost', 'arcana')], max_length=40, null=True, verbose_name='attribute'),
        ),
    ]
