# Generated by Django 3.2.6 on 2021-09-30 13:43

from django.db import migrations


def set_tirakan_spells(apps, schema_editor):
    BaseSpell = apps.get_model('magic', 'BaseSpell')
    BaseSpell.objects.all().update(is_tirakan_spell=True)


class Migration(migrations.Migration):
    dependencies = [
        ('magic', '0019_basespell_is_tirakan_spell'),
    ]

    operations = [
        migrations.RunPython(set_tirakan_spells)
    ]
