# Generated by Django 2.0.5 on 2018-05-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('base_intelligence', models.IntegerField(default=0, verbose_name='Intelligenz')),
                ('base_deftness', models.IntegerField(default=1, verbose_name='base deftness')),
                ('base_strength', models.IntegerField(default=1, verbose_name='base strength')),
                ('base_attractiveness', models.IntegerField(default=1, verbose_name='base attractiveness')),
                ('base_endurance', models.IntegerField(default=1, verbose_name='base endurance')),
                ('base_resistance', models.IntegerField(default=1, verbose_name='base resistance')),
                ('base_quickness', models.IntegerField(default=1, verbose_name='base quickness')),
                ('base_openness', models.IntegerField(default=1, verbose_name='base openness')),
                ('base_conscientiousness', models.IntegerField(default=1, verbose_name='base conscientiousness')),
                ('base_extraversion', models.IntegerField(default=1, verbose_name='base extraversion')),
                ('base_agreeableness', models.IntegerField(default=1, verbose_name='base agreeableness')),
                ('base_neuroticism', models.IntegerField(default=1, verbose_name='base neuroticism')),
                ('shadows', models.ManyToManyField(to='rules.Shadow', verbose_name='Schatten')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.IntegerField(default=0, verbose_name='Basiswert')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Knowledge')),
            ],
            options={
                'ordering': ('knowledge__name_en',),
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.IntegerField(default=0, verbose_name='Basiswert')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Skill')),
            ],
            options={
                'ordering': ('skill__name_en',),
            },
        ),
    ]
