# Generated by Django 2.0.5 on 2018-05-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterskill',
            options={'ordering': ('skill__name_de',)},
        ),
        migrations.AddField(
            model_name='character',
            name='base_bonus_dice',
            field=models.IntegerField(default=0, verbose_name='base bonus dice'),
        ),
        migrations.AddField(
            model_name='character',
            name='base_destiny_dice',
            field=models.IntegerField(default=0, verbose_name='base destiny dice'),
        ),
        migrations.AddField(
            model_name='character',
            name='base_rerolls',
            field=models.IntegerField(default=0, verbose_name='base rerolls'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_agreeableness',
            field=models.IntegerField(default=1, verbose_name='Verträglichkeit Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_attractiveness',
            field=models.IntegerField(default=1, verbose_name='Attraktivität Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_conscientiousness',
            field=models.IntegerField(default=1, verbose_name='Gewissenhaftigkeit Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_deftness',
            field=models.IntegerField(default=1, verbose_name='Geschick Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_endurance',
            field=models.IntegerField(default=1, verbose_name='Ausdauer Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_extraversion',
            field=models.IntegerField(default=1, verbose_name='Extraversion Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_intelligence',
            field=models.IntegerField(default=100, verbose_name='Intelligenz'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_neuroticism',
            field=models.IntegerField(default=1, verbose_name='Neurotizismus Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_openness',
            field=models.IntegerField(default=1, verbose_name='Offenheit Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_quickness',
            field=models.IntegerField(default=1, verbose_name='Schnelligkeit Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_resistance',
            field=models.IntegerField(default=1, verbose_name='Resistenz Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_strength',
            field=models.IntegerField(default=1, verbose_name='Kraft Basis'),
        ),
    ]
