# Generated by Django 2.0.5 on 2018-05-07 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20180507_1832'),
        ('characters', '0003_auto_20180507_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'ordering': ('template__name_de',),
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='base_bonus_dice',
            field=models.IntegerField(default=0, verbose_name='Bonuswürfel Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_destiny_dice',
            field=models.IntegerField(default=0, verbose_name='Schicksalswürfel Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_rerolls',
            field=models.IntegerField(default=0, verbose_name='Wiederholungswürfel Basis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erzeugt von'),
        ),
        migrations.AddField(
            model_name='charactertemplate',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
        migrations.AddField(
            model_name='charactertemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Template'),
        ),
    ]
