# Generated by Django 2.0.5 on 2018-06-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20180507_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erzeugt am'),
        ),
    ]
