# Generated by Django 2.0.5 on 2018-10-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_lineage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='lineage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.Lineage', verbose_name='Abstammung'),
        ),
    ]
