# Generated by Django 2.0.5 on 2018-10-06 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0004_auto_20181006_0029'),
        ('characters', '0007_auto_20181006_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRiotGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField(default=100, verbose_name='condition')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('riot_gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.RiotGear')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('modifications', models.ManyToManyField(to='armory.WeaponModification')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.Weapon')),
            ],
        ),
    ]
