# Generated by Django 2.0.5 on 2018-10-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20181010_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactertemplate',
            options={'ordering': ('template__category__id',)},
        ),
    ]
