# Generated by Django 2.0.5 on 2018-10-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_auto_20181010_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactertemplate',
            options={'ordering': ('template__category__sort_order',)},
        ),
        migrations.AlterField(
            model_name='character',
            name='lineage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rules.Lineage', verbose_name='Abstammung'),
            preserve_default=False,
        ),
    ]
