# Generated by Django 2.0.5 on 2018-10-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0014_auto_20181013_1542'),
        ('characters', '0013_character_creation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='extension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rules.Extension'),
            preserve_default=False,
        ),
    ]
