# Generated by Django 2.0.5 on 2018-10-13 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_character_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='base_agreeableness',
            field=models.IntegerField(default=1, verbose_name='base agreeableness'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_attractiveness',
            field=models.IntegerField(default=1, verbose_name='base attractiveness'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_bonus_dice',
            field=models.IntegerField(default=0, verbose_name='base bonus dice'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_conscientiousness',
            field=models.IntegerField(default=1, verbose_name='base conscientiousness'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_deftness',
            field=models.IntegerField(default=1, verbose_name='base deftness'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_destiny_dice',
            field=models.IntegerField(default=0, verbose_name='base destiny dice'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_endurance',
            field=models.IntegerField(default=1, verbose_name='base endurance'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_extraversion',
            field=models.IntegerField(default=1, verbose_name='base extraversion'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_intelligence',
            field=models.IntegerField(default=100, verbose_name='intelligence'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_neuroticism',
            field=models.IntegerField(default=1, verbose_name='base neuroticism'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_openness',
            field=models.IntegerField(default=1, verbose_name='base openness'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_quickness',
            field=models.IntegerField(default=1, verbose_name='base quickness'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_rerolls',
            field=models.IntegerField(default=0, verbose_name='base rerolls'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_resistance',
            field=models.IntegerField(default=1, verbose_name='base resistance'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_strength',
            field=models.IntegerField(default=1, verbose_name='base strength'),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Characters without user will be cleaned daily.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='character',
            name='creation_mode',
            field=models.CharField(default='random', max_length=12, verbose_name='creation mode'),
        ),
        migrations.AlterField(
            model_name='character',
            name='lineage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Lineage', verbose_name='lineage'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='shadows',
            field=models.ManyToManyField(to='rules.Shadow', verbose_name='shadows'),
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='characterknowledge',
            name='base_value',
            field=models.IntegerField(default=0, verbose_name='base value'),
        ),
        migrations.AlterField(
            model_name='characterriotgear',
            name='condition',
            field=models.IntegerField(default=100, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='base_value',
            field=models.IntegerField(default=0, verbose_name='base value'),
        ),
        migrations.AlterField(
            model_name='charactertemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
