# Generated by Django 2.0.5 on 2018-10-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_auto_20181017_1343'),
        ('characters', '0016_auto_20181017_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='extension',
        ),
        migrations.AddField(
            model_name='character',
            name='extensions',
            field=models.ManyToManyField(limit_choices_to={'is_mandatory': False}, to='rules.Extension'),
        ),
    ]
