# Generated by Django 2.0.13 on 2019-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterweapon',
            name='condition',
            field=models.IntegerField(default=100),
        ),
    ]
