# Generated by Django 2.0.13 on 2019-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_auto_20190411_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name='reputation'),
        ),
        migrations.AddField(
            model_name='character',
            name='reputation_spent',
            field=models.IntegerField(default=0, verbose_name='reputation spent'),
        ),
    ]
