# Generated by Django 2.0.13 on 2019-04-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_auto_20190420_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='reputation_spent',
        ),
    ]
