# Generated by Django 2.0.13 on 2019-04-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20190420_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='base_spell_points',
            field=models.IntegerField(default=0, verbose_name='spell points'),
        ),
    ]
