# Generated by Django 2.0.13 on 2019-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_character_base_spell_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='arcana',
            field=models.IntegerField(default=3, verbose_name='arcana'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_max_arcana',
            field=models.IntegerField(default=0, verbose_name='max arcana'),
        ),
    ]
