# Generated by Django 2.0.13 on 2019-06-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0007_auto_20190617_2136'),
        ('characters', '0025_auto_20190422_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.Spell')),
            ],
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='quantity',
        ),
    ]
