# Generated by Django 2.0.13 on 2019-08-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_auto_20190617_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
