# Generated by Django 2.0.13 on 2019-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_characteritem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to='character_backdrop_images', verbose_name='backdrop image'),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
