# Generated by Django 2.0.13 on 2019-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_auto_20190827_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='base_agreeableness',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_attractiveness',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_bonus_dice',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_conscientiousness',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_deftness',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_destiny_dice',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_endurance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_extraversion',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_max_arcana',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_max_health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_neuroticism',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_openness',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_quickness',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_rerolls',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_resistance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_spell_points',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_strength',
        ),
        migrations.AlterField(
            model_name='character',
            name='shadows',
            field=models.ManyToManyField(blank=True, to='rules.Shadow', verbose_name='shadows'),
        ),
    ]
