# Generated by Django 2.0.13 on 2019-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0029_auto_20191011_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stress',
            field=models.IntegerField(default=0, verbose_name='stress'),
        ),
    ]
