# Generated by Django 2.0.13 on 2019-10-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horror', '0004_auto_20191012_1927'),
        ('characters', '0030_character_stress'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quirks',
            field=models.ManyToManyField(blank=True, to='horror.Quirk', verbose_name='quirks'),
        ),
    ]
