# Generated by Django 2.2.14 on 2020-07-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0032_characterstatuseffect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterstatuseffect',
            options={'ordering': ('status_effect__ordering',)},
        ),
    ]
