# Generated by Django 2.2.14 on 2020-12-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0033_auto_20200706_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='creation_mode',
        ),
    ]
