# Generated by Django 2.2.14 on 2021-02-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20191011_1355'),
        ('characters', '0034_remove_character_creation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Campaign', verbose_name='Campaign'),
        ),
    ]
