# Generated by Django 2.2.18 on 2021-03-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0035_character_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonus_dice_used',
            field=models.IntegerField(default=0, verbose_name='Bonus dice used'),
        ),
        migrations.AddField(
            model_name='character',
            name='destiny_dice_used',
            field=models.IntegerField(default=0, verbose_name='Destiny dice used'),
        ),
        migrations.AddField(
            model_name='character',
            name='rerolls_used',
            field=models.IntegerField(default=0, verbose_name='Rerolls used'),
        ),
    ]
