# Generated by Django 2.2.18 on 2021-03-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0036_auto_20210308_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='shadows',
        ),
        migrations.DeleteModel(
            name='CharacterKnowledge',
        ),
    ]
