# Generated by Django 2.2.18 on 2021-05-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0037_auto_20210313_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterweapon',
            name='capacity_used',
            field=models.IntegerField(default=0, verbose_name='capacity used'),
        ),
    ]
