# Generated by Django 3.2.5 on 2021-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0038_characterweapon_capacity_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskill',
            name='base_value',
            field=models.IntegerField(default=1, verbose_name='base value'),
        ),
    ]
