# Generated by Django 3.2.5 on 2021-07-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0039_alter_characterskill_base_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterSpell',
        ),
    ]
