# Generated by Django 3.2.5 on 2021-08-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0014_auto_20210726_1257'),
        ('characters', '0041_auto_20210726_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.basespell')),
            ],
            options={
                'ordering': ('spell__id',),
            },
        ),
        migrations.CreateModel(
            name='CharacterSpellTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.characterspell')),
                ('spell_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.spelltemplate')),
            ],
        ),
    ]
