# Generated by Django 3.2.5 on 2021-08-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0042_characterspell_characterspelltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterspell',
            name='custom_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='custom name'),
        ),
    ]
