# Generated by Django 3.2.7 on 2021-10-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0043_characterspell_custom_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteritem',
            options={'ordering': ('item__id',)},
        ),
        migrations.AlterModelOptions(
            name='characterriotgear',
            options={'ordering': ('riot_gear__id',)},
        ),
    ]
