# Generated by Django 2.2.18 on 2021-04-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0049_remove_knowledge_add_to_all_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'foe type',
                'verbose_name_plural': 'foe types',
            },
        ),
        migrations.CreateModel(
            name='Foe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('name_de', models.CharField(max_length=256, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('extensions', models.ManyToManyField(to='rules.Extension')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.FoeType', verbose_name='type')),
            ],
            options={
                'verbose_name': 'foe',
                'verbose_name_plural': 'foes',
            },
        ),
    ]
