# Generated by Django 2.2.18 on 2021-04-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoeResistanceOrWeakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'foe resistance or weakness',
                'verbose_name_plural': 'foe resistances or weaknesses',
            },
        ),
        migrations.RenameField(
            model_name='foe',
            old_name='description',
            new_name='description_de',
        ),
        migrations.AddField(
            model_name='foe',
            name='actions',
            field=models.IntegerField(default=2, verbose_name='actions'),
        ),
        migrations.AddField(
            model_name='foe',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='foe',
            name='health',
            field=models.IntegerField(default=6, verbose_name='health'),
        ),
        migrations.AddField(
            model_name='foe',
            name='minimum_roll',
            field=models.IntegerField(default=5, verbose_name='minimum_roll'),
        ),
        migrations.AddField(
            model_name='foe',
            name='movement',
            field=models.IntegerField(default=1, verbose_name='movement'),
        ),
        migrations.CreateModel(
            name='FoeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('effect', models.TextField(verbose_name='effect')),
                ('foe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Foe', verbose_name='foe')),
            ],
        ),
        migrations.AddField(
            model_name='foe',
            name='resistances',
            field=models.ManyToManyField(related_name='foe_resistance_set', to='bestiary.FoeResistanceOrWeakness', verbose_name='resistances'),
        ),
        migrations.AddField(
            model_name='foe',
            name='weaknesses',
            field=models.ManyToManyField(related_name='foe_weakness_set', to='bestiary.FoeResistanceOrWeakness', verbose_name='weaknesses'),
        ),
    ]
