# Generated by Django 2.2.18 on 2021-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_auto_20210417_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='foeaction',
            name='skill',
            field=models.IntegerField(default=6, verbose_name='skill'),
        ),
    ]
