# Generated by Django 2.2.18 on 2021-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0003_foeaction_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foeaction',
            options={'verbose_name': 'foe action', 'verbose_name_plural': 'foe actions'},
        ),
        migrations.RenameField(
            model_name='foeaction',
            old_name='effect',
            new_name='effect_de',
        ),
        migrations.RenameField(
            model_name='foeaction',
            old_name='name',
            new_name='name_de',
        ),
        migrations.AddField(
            model_name='foeaction',
            name='effect_en',
            field=models.TextField(blank=True, null=True, verbose_name='effect'),
        ),
        migrations.AddField(
            model_name='foeaction',
            name='name_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
    ]
