# Generated by Django 2.2.18 on 2021-04-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0004_auto_20210417_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foe',
            name='minimum_roll',
            field=models.IntegerField(default=5, verbose_name='minimum roll'),
        ),
        migrations.AlterField(
            model_name='foe',
            name='resistances',
            field=models.ManyToManyField(blank=True, related_name='foe_resistance_set', to='bestiary.FoeResistanceOrWeakness', verbose_name='resistances'),
        ),
        migrations.AlterField(
            model_name='foe',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='foe_weakness_set', to='bestiary.FoeResistanceOrWeakness', verbose_name='weaknesses'),
        ),
    ]
