# Generated by Django 2.2.18 on 2021-04-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0005_auto_20210417_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='foe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foe_images', verbose_name='image'),
        ),
    ]
