# Generated by Django 2.0.13 on 2019-10-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0036_auto_20191011_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quirk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'quirk',
                'verbose_name_plural': 'quirks',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuirkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=30, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'quirk category',
                'verbose_name_plural': 'quirk categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuirkModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, choices=[('base_intelligence', 'intelligence'), ('base_max_health', 'max health'), ('base_max_arcana', 'max arcana'), ('base_spell_points', 'spell points'), ('base_bonus_dice', 'bonus dice'), ('base_destiny_dice', 'destiny dice'), ('base_rerolls', 'rerolls'), ('base_deftness', 'deftness'), ('base_strength', 'strength'), ('base_attractiveness', 'attractiveness'), ('base_endurance', 'endurance'), ('base_resistance', 'resistance'), ('base_quickness', 'quickness'), ('base_openness', 'openness'), ('base_conscientiousness', 'conscientiousness'), ('base_extraversion', 'extraversion'), ('base_agreeableness', 'agreeableness'), ('base_neuroticism', 'neuroticism')], max_length=40, null=True, verbose_name='attribute')),
                ('attribute_modifier', models.IntegerField(blank=True, null=True, verbose_name='attribute modifier')),
                ('skill_modifier', models.IntegerField(blank=True, null=True, verbose_name='skill modifier')),
                ('quirk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horror.Quirk', verbose_name='quirk')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Skill', verbose_name='skill')),
            ],
        ),
    ]
