# Generated by Django 2.0.13 on 2019-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horror', '0003_auto_20191011_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quirk',
            name='name_de',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='quirk',
            name='name_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='name'),
        ),
    ]
