# Generated by Django 2.2.18 on 2021-05-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horror', '0005_alter_quirkmodifier_attribute'),
        ('horror', '0005_auto_20210531_0412'),
    ]

    operations = [
    ]
