# Generated by Django 2.2.5 on 2019-10-02 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0028_auto_20190827_1314'),
        ('rules', '0035_extension_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign_images', verbose_name='image')),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='campaign_backdrop_images', verbose_name='backdrop image')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='abstract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('extensions', models.ManyToManyField(limit_choices_to={'is_mandatory': False}, to='rules.Extension')),
                ('forbidden_templates', models.ManyToManyField(to='rules.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('npc', models.ManyToManyField(to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign_handouts', verbose_name='image')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Scene')),
            ],
        ),
    ]
