# Generated by Django 2.2.5 on 2019-10-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0035_extension_image'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='epoch',
            field=models.ForeignKey(default=1, limit_choices_to={'is_epoch': True}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_epoch_set', to='rules.Extension'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='extensions',
            field=models.ManyToManyField(limit_choices_to={'is_epoch': False, 'is_mandatory': False}, to='rules.Extension'),
        ),
    ]
