# Generated by Django 2.0.13 on 2019-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20191002_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='extensions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_epoch': False, 'is_mandatory': False}, to='rules.Extension'),
        ),
    ]
