# Generated by Django 2.0.5 on 2018-06-30 17:24

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='text_de',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='text_en',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True, verbose_name='text'),
        ),
    ]
