# Generated by Django 2.0.5 on 2018-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0004_auto_20180919_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='fa_icon_class',
            field=models.CharField(default='fa fa-book', max_length=30, verbose_name='FA Icon Klasse'),
        ),
    ]
