# Generated by Django 2.0.13 on 2019-11-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0006_chapter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='extension',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
