# Generated by Django 2.0.5 on 2018-05-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'verbose_name': 'Vorlagenkategorie', 'verbose_name_plural': 'Vorlagenkategorien'},
        ),
    ]
