# Generated by Django 2.0.5 on 2018-05-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20180507_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodifier',
            name='shadow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Shadow', verbose_name='Schatten'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='attribute',
            field=models.CharField(blank=True, choices=[('base_intelligence', 'Intelligenz'), ('base_deftness', 'Geschick'), ('base_strength', 'Kraft'), ('base_attractiveness', 'Attraktivität'), ('base_endurance', 'Ausdauer'), ('base_resistance', 'Resistenz'), ('base_quickness', 'Schnelligkeit'), ('base_openness', 'Offenheit'), ('base_conscientiousness', 'Gewissenhaftigkeit'), ('base_extraversion', 'Extraversion'), ('base_agreeableness', 'Verträglichkeit'), ('base_neuroticism', 'Neurotizismus')], max_length=40, null=True, verbose_name='Attribut'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='attribute_modifier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attributsmodifikator'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Knowledge', verbose_name='Wissen'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='knowledge_modifier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wissensmodifikator'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Skill', verbose_name='Fertigkeit'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='skill_modifier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fertigkeitsmodifikator'),
        ),
    ]
