# Generated by Django 2.0.5 on 2018-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20180507_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadow',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='shadow',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
    ]
