# Generated by Django 2.0.5 on 2018-09-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_auto_20180930_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=80, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'lineage',
                'verbose_name_plural': 'lineages',
            },
        ),
        migrations.CreateModel(
            name='LineageTemplatePoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='points')),
                ('lineage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Lineage', verbose_name='lineage')),
                ('template_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.TemplateCategory', verbose_name='Vorlagenkategorie')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='kind',
            field=models.CharField(choices=[('p', 'praktisch'), ('m', 'geistig')], max_length=1, verbose_name='Art'),
        ),
    ]
