# Generated by Django 2.0.5 on 2018-10-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_auto_20180930_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineage',
            options={'verbose_name': 'Abstammung', 'verbose_name_plural': 'Abstammungen'},
        ),
        migrations.AddField(
            model_name='lineage',
            name='extension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rules.Extension'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineagetemplatepoints',
            name='lineage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Lineage', verbose_name='Abstammung'),
        ),
    ]
