# Generated by Django 2.0.5 on 2018-10-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_auto_20181006_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='bootstrap_color_class',
            field=models.CharField(choices=[('', '-'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('muted', 'muted'), ('white', 'white')], default='', max_length=10, verbose_name='bootstrap color class'),
        ),
        migrations.AlterField(
            model_name='lineagetemplatepoints',
            name='points',
            field=models.IntegerField(verbose_name='Punkte'),
        ),
    ]
