# Generated by Django 2.0.5 on 2018-10-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_auto_20181010_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'verbose_name': 'Schablonenkategorie', 'verbose_name_plural': 'Schablonenkategorien'},
        ),
        migrations.RenameField(
            model_name='templatecategory',
            old_name='bootstrap_color_class',
            new_name='bg_color_class',
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='fg_color_class',
            field=models.CharField(choices=[('', '-'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('muted', 'muted'), ('white', 'white')], default='', max_length=10, verbose_name='bootstrap color class'),
        ),
        migrations.AlterField(
            model_name='lineagetemplatepoints',
            name='template_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.TemplateCategory', verbose_name='Schablonenkategorie'),
        ),
    ]
