# Generated by Django 2.0.5 on 2018-10-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0012_auto_20181010_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='sort_order',
            field=models.IntegerField(default=1000, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='bg_color_class',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('muted', 'muted'), ('white', 'white')], default='', max_length=10, verbose_name='Bootstrap Farbklasse'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='fg_color_class',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('muted', 'muted'), ('white', 'white')], default='', max_length=10, verbose_name='Bootstrap Farbklasse'),
        ),
    ]
