# Generated by Django 2.0.5 on 2018-10-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0013_auto_20181010_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('category__sort_order',), 'verbose_name': 'Charakterschablone', 'verbose_name_plural': 'Charakterschablonen'},
        ),
    ]
