# Generated by Django 2.0.5 on 2018-10-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0014_auto_20181013_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'verbose_name': 'extension', 'verbose_name_plural': 'extensions'},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name': 'knowledge', 'verbose_name_plural': 'knowledge'},
        ),
        migrations.AlterModelOptions(
            name='lineage',
            options={'verbose_name': 'lineage', 'verbose_name_plural': 'lineages'},
        ),
        migrations.AlterModelOptions(
            name='shadow',
            options={'verbose_name': 'shadow', 'verbose_name_plural': 'shadows'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('category__sort_order',), 'verbose_name': 'character template', 'verbose_name_plural': 'character templates'},
        ),
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'verbose_name': 'template category', 'verbose_name_plural': 'template categories'},
        ),
        migrations.AlterField(
            model_name='extension',
            name='is_mandatory',
            field=models.BooleanField(default=False, verbose_name='is mandatory'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='name_de',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='add_to_all_characters',
            field=models.BooleanField(default=True, verbose_name='add to all characters'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='name_de',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='name_de',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lineagetemplatepoints',
            name='lineage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Lineage', verbose_name='lineage'),
        ),
        migrations.AlterField(
            model_name='lineagetemplatepoints',
            name='points',
            field=models.IntegerField(verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='lineagetemplatepoints',
            name='template_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.TemplateCategory', verbose_name='template category'),
        ),
        migrations.AlterField(
            model_name='shadow',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='shadow',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='shadow',
            name='name_de',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='shadow',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='kind',
            field=models.CharField(choices=[('p', 'practical'), ('m', 'mind')], max_length=1, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name_de',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.TemplateCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='template',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_de',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='bg_color_class',
            field=models.CharField(blank=True, choices=[('', 'None'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('muted', 'muted'), ('white', 'white')], default='', max_length=10, verbose_name='bootstrap color class'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='fg_color_class',
            field=models.CharField(blank=True, choices=[('', 'None'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('muted', 'muted'), ('white', 'white')], default='', max_length=10, verbose_name='bootstrap color class'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='name_de',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='attribute',
            field=models.CharField(blank=True, choices=[('base_intelligence', 'intelligence'), ('base_bonus_dice', 'bonus dice'), ('base_destiny_dice', 'destiny dice'), ('base_rerolls', 'rerolls'), ('base_deftness', 'deftness'), ('base_strength', 'strength'), ('base_attractiveness', 'attractiveness'), ('base_endurance', 'endurance'), ('base_resistance', 'resistance'), ('base_quickness', 'quickness'), ('base_openness', 'openness'), ('base_conscientiousness', 'conscientiousness'), ('base_extraversion', 'extraversion'), ('base_agreeableness', 'agreeableness'), ('base_neuroticism', 'neuroticism')], max_length=40, null=True, verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='attribute_modifier',
            field=models.IntegerField(blank=True, null=True, verbose_name='attribute modifier'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Knowledge', verbose_name='knowledge'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='knowledge_modifier',
            field=models.IntegerField(blank=True, null=True, verbose_name='knowledge modifier'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='shadow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Shadow', verbose_name='shadow'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Skill', verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='skill_modifier',
            field=models.IntegerField(blank=True, null=True, verbose_name='skill modifier'),
        ),
        migrations.AlterField(
            model_name='templatemodifier',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Template', verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='templaterequirement',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Template', verbose_name='template'),
        ),
    ]
