# Generated by Django 2.0.5 on 2018-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_auto_20181017_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='fa_icon_class',
            field=models.CharField(default='fa fa-book', max_length=30, verbose_name='FA Icon Class'),
        ),
    ]
