# Generated by Django 2.0.5 on 2018-11-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0017_extension_fa_icon_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'ordering': ('id',), 'verbose_name': 'extension', 'verbose_name_plural': 'extensions'},
        ),
        migrations.AlterModelOptions(
            name='lineagetemplatepoints',
            options={'ordering': ('template_category__sort_order',)},
        ),
    ]
