# Generated by Django 2.0.5 on 2018-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0018_auto_20181102_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='show_on_combat_tab',
            field=models.BooleanField(default=False, verbose_name='show on combat tab'),
        ),
    ]
