# Generated by Django 2.0.13 on 2019-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0024_auto_20190420_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='identifier',
            field=models.CharField(default='def', max_length=20, verbose_name='name'),
            preserve_default=False,
        ),
    ]
