# Generated by Django 2.0.13 on 2019-06-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0026_auto_20190422_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='allow_for_reputation',
            field=models.BooleanField(default=True, verbose_name='Allow for reputation'),
        ),
    ]
