# Generated by Django 2.0.13 on 2019-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0027_templatecategory_allow_for_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='quote'),
        ),
    ]
