# Generated by Django 2.0.13 on 2019-07-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0029_template_quote_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='template',
            name='description_en',
        ),
        migrations.AddField(
            model_name='template',
            name='rules_de',
            field=models.TextField(blank=True, null=True, verbose_name='rules'),
        ),
        migrations.AddField(
            model_name='template',
            name='rules_en',
            field=models.TextField(blank=True, null=True, verbose_name='rules'),
        ),
    ]
