# Generated by Django 2.0.13 on 2019-07-30 04:22

from django.db import migrations


def copy_extensions(apps, schema_editor):
    Item = apps.get_model('armory.Item')
    Weapon = apps.get_model('armory.Weapon')
    WeaponModification = apps.get_model('armory.WeaponModification')
    RiotGear = apps.get_model('armory.RiotGear')
    Lineage = apps.get_model('rules.Lineage')
    Skill = apps.get_model('rules.Skill')
    Knowledge = apps.get_model('rules.Knowledge')
    Shadow = apps.get_model('rules.Shadow')
    Template = apps.get_model('rules.Template')

    for x in Item.objects.all():
        x.extensions.set([x.extension])
    for x in Weapon.objects.all():
        x.extensions.set([x.extension])
    for x in WeaponModification.objects.all():
        x.extensions.set([x.extension])
    for x in RiotGear.objects.all():
        x.extensions.set([x.extension])
    for x in Lineage.objects.all():
        x.extensions.set([x.extension])
    for x in Skill.objects.all():
        x.extensions.set([x.extension])
    for x in Knowledge.objects.all():
        x.extensions.set([x.extension])
    for x in Shadow.objects.all():
        x.extensions.set([x.extension])
    for x in Template.objects.all():
        x.extensions.set([x.extension])


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0031_auto_20190730_0421'),
    ]

    operations = [
        migrations.RunPython(copy_extensions)
    ]
