# Generated by Django 2.0.13 on 2019-08-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0032_auto_20190730_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='lineage',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='shadow',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='template',
            name='extension',
        ),
    ]
