# Generated by Django 2.0.13 on 2019-08-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0033_auto_20190805_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'ordering': ('ordering',), 'verbose_name': 'extension', 'verbose_name_plural': 'extensions'},
        ),
        migrations.AddField(
            model_name='extension',
            name='ordering',
            field=models.IntegerField(default=100, verbose_name='ordering'),
        ),
    ]
