# Generated by Django 2.0.13 on 2019-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0035_extension_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineage',
            name='base_agreeableness',
            field=models.IntegerField(default=1, verbose_name='base agreeableness'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_attractiveness',
            field=models.IntegerField(default=1, verbose_name='base attractiveness'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_bonus_dice',
            field=models.IntegerField(default=0, verbose_name='base bonus dice'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_conscientiousness',
            field=models.IntegerField(default=1, verbose_name='base conscientiousness'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_deftness',
            field=models.IntegerField(default=1, verbose_name='base deftness'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_destiny_dice',
            field=models.IntegerField(default=0, verbose_name='base destiny dice'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_endurance',
            field=models.IntegerField(default=1, verbose_name='base endurance'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_extraversion',
            field=models.IntegerField(default=1, verbose_name='base extraversion'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_intelligence',
            field=models.IntegerField(default=100, verbose_name='intelligence'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_max_arcana',
            field=models.IntegerField(default=0, verbose_name='max arcana'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_max_health',
            field=models.IntegerField(default=6, verbose_name='max health'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_neuroticism',
            field=models.IntegerField(default=1, verbose_name='base neuroticism'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_openness',
            field=models.IntegerField(default=1, verbose_name='base openness'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_quickness',
            field=models.IntegerField(default=1, verbose_name='base quickness'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_rerolls',
            field=models.IntegerField(default=0, verbose_name='base rerolls'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_resistance',
            field=models.IntegerField(default=1, verbose_name='base resistance'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_spell_points',
            field=models.IntegerField(default=0, verbose_name='spell points'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_strength',
            field=models.IntegerField(default=1, verbose_name='base strength'),
        ),
    ]
