# Generated by Django 2.2.14 on 2020-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0037_auto_20191011_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_icon_class', models.CharField(default='fa fa-book', max_length=30, verbose_name='FA Icon Class')),
                ('name_de', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'status effect',
                'verbose_name_plural': 'status effects',
            },
        ),
    ]
