# Generated by Django 2.2.14 on 2020-07-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0038_statuseffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuseffect',
            name='rules_de',
            field=models.TextField(blank=True, null=True, verbose_name='rules'),
        ),
        migrations.AddField(
            model_name='statuseffect',
            name='rules_en',
            field=models.TextField(blank=True, null=True, verbose_name='rules'),
        ),
    ]
