# Generated by Django 2.2.14 on 2020-07-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0039_auto_20200705_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuseffect',
            name='extensions',
            field=models.ManyToManyField(to='rules.Extension'),
        ),
    ]
