# Generated by Django 2.2.14 on 2020-07-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0040_statuseffect_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='fa_icon_class',
            field=models.CharField(default='fas fa-book', max_length=30, verbose_name='FA Icon Class'),
        ),
        migrations.AlterField(
            model_name='statuseffect',
            name='fa_icon_class',
            field=models.CharField(default='fas fa-book', max_length=30, verbose_name='FA Icon Class'),
        ),
    ]
