# Generated by Django 2.2.14 on 2020-07-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0041_auto_20200705_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuseffect',
            options={'ordering': ('ordering',), 'verbose_name': 'status effect', 'verbose_name_plural': 'status effects'},
        ),
        migrations.AddField(
            model_name='statuseffect',
            name='ordering',
            field=models.IntegerField(default=100, verbose_name='ordering'),
        ),
    ]
