# Generated by Django 2.2.14 on 2020-09-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0042_auto_20200706_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineage',
            name='base_evasion',
            field=models.IntegerField(default=0, verbose_name='base evasion'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='base_protection',
            field=models.IntegerField(default=0, verbose_name='base armor'),
        ),
    ]
