# Generated by Django 2.2.14 on 2021-01-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0045_skill_default_persona_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='default_persona_attribute',
            field=models.CharField(blank=True, choices=[('intelligence', 'intelligence'), ('openness', 'openness'), ('conscientiousness', 'conscientiousness'), ('extraversion', 'extraversion'), ('agreeableness', 'agreeableness'), ('neuroticism', 'neuroticism')], default='openness', max_length=20, null=True, verbose_name='default persona attribute'),
        ),
    ]
