# Generated by Django 2.2.18 on 2021-02-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0046_auto_20210116_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='default_persona_attribute',
        ),
    ]
