# Generated by Django 2.2.18 on 2021-03-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0047_remove_skill_default_persona_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.Skill', verbose_name='Skill'),
        ),
    ]
