# Generated by Django 2.2.18 on 2021-04-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0049_remove_knowledge_add_to_all_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineage',
            name='base_actions',
            field=models.IntegerField(default=2, verbose_name='base actions'),
        ),
    ]
