# Generated by Django 2.2.18 on 2021-05-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0051_auto_20210531_0412'),
        ('rules', '0051_alter_templatemodifier_attribute'),
    ]

    operations = [
    ]
