# Generated by Django 3.2.5 on 2021-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0053_extension_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='show_rules_in_combat',
            field=models.BooleanField(default=False, help_text='Show the rule as combat action on the combat tab.', verbose_name='Show rules in combat'),
        ),
        migrations.AddField(
            model_name='template',
            name='show_rules_in_shadows',
            field=models.BooleanField(default=False, help_text='Show the rule as shadow on the main character sheet.', verbose_name='Show rules in shadows'),
        ),
    ]
