# Generated by Django 3.2.5 on 2021-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0055_auto_20210716_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='dominant_attribute',
            field=models.CharField(blank=True, choices=[('deftness', 'deftness'), ('strength', 'strength'), ('attractiveness', 'attractiveness'), ('endurance', 'endurance'), ('resistance', 'resistance'), ('quickness', 'quickness'), ('logic', 'logic'), ('education', 'education'), ('conscientiousness', 'conscientiousness'), ('willpower', 'willpower'), ('apprehension', 'apprehension'), ('charm', 'charm')], max_length=20, null=True, verbose_name='dominant attribute'),
        ),
        migrations.AddField(
            model_name='skill',
            name='supplemental_attribute',
            field=models.CharField(blank=True, choices=[('deftness', 'deftness'), ('strength', 'strength'), ('attractiveness', 'attractiveness'), ('endurance', 'endurance'), ('resistance', 'resistance'), ('quickness', 'quickness'), ('logic', 'logic'), ('education', 'education'), ('conscientiousness', 'conscientiousness'), ('willpower', 'willpower'), ('apprehension', 'apprehension'), ('charm', 'charm')], max_length=20, null=True, verbose_name='supplemental attribute'),
        ),
    ]
