# Generated by Django 3.2.5 on 2021-07-16 20:05

from django.db import migrations

def skill_changes(apps, schema_editor):
    Skill = apps.get_model('rules', 'Skill')
    Character = apps.get_model('characters', 'Character')
    CharacterSkill = apps.get_model('characters', 'CharacterSkill')

    Skill.objects.get(name_en='Willpower').delete()

    s = Skill.objects.get(name_en='Mindfulness')
    s.dominant_attribute = 'apprehension'
    s.supplemental_attribute = 'conscientiousness'
    s.save()

    s = Skill.objects.get(name_en='Perception')
    s.dominant_attribute = 'apprehension'
    s.supplemental_attribute = 'quickness'
    s.save()

    s = Skill.objects.get(name_en='Communication')
    s.dominant_attribute = 'education'
    s.supplemental_attribute = 'charm'
    s.save()

    s = Skill.objects.get(name_en='Intimidation')
    s.dominant_attribute = 'apprehension'
    s.supplemental_attribute = 'willpower'
    s.save()

    s = Skill.objects.get(name_en='Empathy')
    s.dominant_attribute = 'conscientiousness'
    s.supplemental_attribute = 'charm'
    s.save()

    s = Skill.objects.get(name_en='Stealth')
    s.dominant_attribute = 'conscientiousness'
    s.supplemental_attribute = 'deftness'
    s.save()

    s = Skill.objects.get(name_en='Orientation')
    s.dominant_attribute = 'apprehension'
    s.supplemental_attribute = 'logic'
    s.save()

    s = Skill.objects.get(name_en='Courage')
    s.dominant_attribute = 'willpower'
    s.supplemental_attribute = 'resistance'
    s.save()

    s = Skill.objects.get(name_en='Deception')
    s.dominant_attribute = 'attractiveness'
    s.supplemental_attribute = 'charm'
    s.save()

    s = Skill.objects.get(name_en='Persuasion')
    s.dominant_attribute = 'willpower'
    s.supplemental_attribute = 'attractiveness'
    s.save()

    s = Skill.objects.get(name_en='Athleticism')
    s.dominant_attribute = 'strength'
    s.supplemental_attribute = 'endurance'
    s.save()

    s = Skill.objects.get(name_en='First Aid')
    s.dominant_attribute = 'education'
    s.supplemental_attribute = 'conscientiousness'
    s.save()

    s = Skill.objects.get(name_en='Driving')
    s.dominant_attribute = 'deftness'
    s.supplemental_attribute = 'apprehension'
    s.save()

    s = Skill.objects.get(name_en='Mechanics')
    s.dominant_attribute = 'education'
    s.supplemental_attribute = 'logic'
    s.save()

    s = Skill.objects.get(name_en='Hand to Hand Combat')
    s.dominant_attribute = 'strength'
    s.supplemental_attribute = 'deftness'
    s.save()

    s = Skill.objects.get(name_en='Shooting')
    s.dominant_attribute = 'deftness'
    s.supplemental_attribute = 'strength'
    s.save()

    s = Skill.objects.get(name_en='Throwing')
    s.dominant_attribute = 'deftness'
    s.supplemental_attribute = 'strength'
    s.save()

    s = Skill.objects.get(name_en="Esthetics")
    s.name_en = 'Peformance'
    s.name_de = 'Darbietung'
    s.dominant_attribute = 'charm'
    s.supplemental_attribute = 'deftness'
    s.save()

    s = Skill.objects.get(name_en="Improvising")
    s.name_en = 'Acrobatics'
    s.name_de = 'Akrobatik'
    s.dominant_attribute = 'deftness'
    s.supplemental_attribute = 'quickness'
    s.save()

    investigation = Skill.objects.create(
        name_en="Investigation",
        name_de="Untersuchen",
        dominant_attribute="logic",
        supplemental_attribute="apprehension",
        kind="m"
    )

    nature = Skill.objects.create(
        name_en="Nature",
        name_de="Naturkunde",
        dominant_attribute="education",
        supplemental_attribute="logic",
        kind="p"
    )

    history = Skill.objects.create(
        name_en="History",
        name_de="Historie",
        dominant_attribute="education",
        supplemental_attribute="conscientiousness",
        kind="p"
    )

    politics = Skill.objects.create(
        name_en="Politics",
        name_de="Politik",
        dominant_attribute="education",
        supplemental_attribute="charm",
        kind="m"
    )

    religion = Skill.objects.create(
        name_en="Religion",
        name_de="Religion",
        dominant_attribute="education",
        supplemental_attribute="willpower",
        kind="m"
    )

    for c in Character.objects.all():
        c.characterskill_set.create(skill=investigation, base_value=0)
        c.characterskill_set.create(skill=nature, base_value=0)
        c.characterskill_set.create(skill=history, base_value=0)
        c.characterskill_set.create(skill=politics, base_value=0)
        c.characterskill_set.create(skill=religion, base_value=0)

    CharacterSkill.objects.all().update(base_value=0)

class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0056_auto_20210716_2001'),
    ]

    operations = [
        migrations.RunPython(skill_changes)
    ]
