# Generated by Django 2.0.5 on 2018-10-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0010_auto_20181006_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=256, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('concealment', models.IntegerField(default=0, verbose_name='concealment')),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to='item_images/', verbose_name='image')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'item type',
                'verbose_name_plural': 'item types',
            },
        ),
        migrations.CreateModel(
            name='RiotGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=256, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('protection_ballistic', models.IntegerField(default=0, verbose_name='protection ballistic')),
                ('protection_explosive', models.IntegerField(default=0, verbose_name='protection explosive')),
                ('concealment', models.IntegerField(default=0, verbose_name='concealment')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension')),
            ],
            options={
                'verbose_name': 'riot gear',
                'verbose_name_plural': 'riot gear',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=256, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('attacks_per_action', models.IntegerField(verbose_name='attacks per action')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('wound_bonus', models.IntegerField(default=0, verbose_name='wound bonus')),
                ('penetration', models.IntegerField(default=0, verbose_name='penetration')),
                ('recoil_control', models.IntegerField(default=0, verbose_name='recoil control')),
                ('concealment', models.IntegerField(default=0, verbose_name='concealment')),
                ('accuracy', models.IntegerField(default=0, verbose_name='accuracy')),
                ('reload_actions', models.IntegerField(default=1, verbose_name='reload actions')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('fire_modes', models.CharField(blank=True, max_length=256, null=True, verbose_name='fire modes')),
                ('range_lower', models.CharField(choices=[('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], default='s', max_length=1, verbose_name='lower range')),
                ('range_upper', models.CharField(blank=True, choices=[('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], max_length=1, null=True, verbose_name='upper range')),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to='weapon_images/', verbose_name='image')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension')),
            ],
            options={
                'verbose_name': 'weapon',
                'verbose_name_plural': 'weapons',
            },
        ),
        migrations.CreateModel(
            name='WeaponModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=40, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
            ],
            options={
                'verbose_name': 'weapon modification',
                'verbose_name_plural': 'weapon modification',
            },
        ),
        migrations.CreateModel(
            name='WeaponModificationAttributeChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('attacks_per_action', 'attacks_per_action'), ('ammunition', 'ammunition'), ('wound_bonus', 'wound_bonus'), ('penetration', 'penetration'), ('accuracy', 'accuracy'), ('weight', 'weight'), ('recoil_control', 'recoil_control'), ('concealment', 'concealment'), ('reload_actions', 'reload_actions')], max_length=40, verbose_name='Attribut')),
                ('modifier', models.IntegerField(default=0, verbose_name='modifier')),
                ('weapon_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.WeaponModification')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponModificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=20, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('unique_equip', models.BooleanField(default=False, help_text='A weapon may only have one modification of this type (i.E. sights)', verbose_name='unique equip')),
            ],
            options={
                'verbose_name': 'weapon modification type',
                'verbose_name_plural': 'weapon modification type',
            },
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'weapon type',
                'verbose_name_plural': 'weapon types',
            },
        ),
        migrations.AddField(
            model_name='weaponmodification',
            name='available_for_weapon_types',
            field=models.ManyToManyField(to='armory.WeaponType'),
        ),
        migrations.AddField(
            model_name='weaponmodification',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Extension'),
        ),
        migrations.AddField(
            model_name='weaponmodification',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.WeaponModificationType'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.WeaponType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.ItemType', verbose_name='type'),
        ),
    ]
