# Generated by Django 2.0.5 on 2018-10-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0002_weapon_is_hand_to_hand_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponAttackMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'attack mode',
                'verbose_name_plural': 'attack modes',
            },
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='fire_modes',
        ),
        migrations.AddField(
            model_name='weapon',
            name='attack_modes',
            field=models.ManyToManyField(to='armory.WeaponAttackMode', verbose_name='attackmodes'),
        ),
    ]
