# Generated by Django 2.0.5 on 2018-10-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0003_auto_20181006_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='attack_modes',
            field=models.ManyToManyField(to='armory.WeaponAttackMode', verbose_name='attack modes'),
        ),
    ]
