# Generated by Django 2.0.5 on 2018-10-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0004_auto_20181006_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_lower',
            field=models.CharField(choices=[('-', 'hand to hand'), ('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], default='s', max_length=1, verbose_name='lower range'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_upper',
            field=models.CharField(blank=True, choices=[('-', 'hand to hand'), ('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], max_length=1, null=True, verbose_name='upper range'),
        ),
    ]
