# Generated by Django 2.0.5 on 2018-10-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0005_auto_20181006_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Gegenstand', 'verbose_name_plural': 'Gegenstände'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'Gegenstandstyp', 'verbose_name_plural': 'Gegenstandstypen'},
        ),
        migrations.AlterModelOptions(
            name='riotgear',
            options={'verbose_name': 'Rüstung', 'verbose_name_plural': 'Rüstung'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Waffe', 'verbose_name_plural': 'Waffen'},
        ),
        migrations.AlterModelOptions(
            name='weaponattackmode',
            options={'verbose_name': 'Angriffsmodus', 'verbose_name_plural': 'Angriffsmodi'},
        ),
        migrations.AlterModelOptions(
            name='weaponmodification',
            options={'verbose_name': 'Waffenmodifikation', 'verbose_name_plural': 'Waffenmodifikation'},
        ),
        migrations.AlterModelOptions(
            name='weaponmodificationtype',
            options={'verbose_name': 'Waffenmodifikationstyp', 'verbose_name_plural': 'Waffenmodifikationstyp'},
        ),
        migrations.AlterModelOptions(
            name='weapontype',
            options={'verbose_name': 'Waffentyp', 'verbose_name_plural': 'Waffentypen'},
        ),
        migrations.AlterField(
            model_name='item',
            name='concealment',
            field=models.IntegerField(default=0, verbose_name='Verborgenheit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='item_images/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.ItemType', verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gewicht'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='concealment',
            field=models.IntegerField(default=0, verbose_name='Verborgenheit'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='protection_ballistic',
            field=models.IntegerField(default=0, verbose_name='Ballistischer Schutz'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='protection_explosive',
            field=models.IntegerField(default=0, verbose_name='Explosivschutz'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gewicht'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='accuracy',
            field=models.IntegerField(default=0, verbose_name='Genauigkeit'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='attack_modes',
            field=models.ManyToManyField(to='armory.WeaponAttackMode', verbose_name='Angriffsmodi'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='attacks_per_action',
            field=models.IntegerField(verbose_name='Angriffe pro Aktion'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kapazität'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='concealment',
            field=models.IntegerField(default=0, verbose_name='Verborgenheit'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='weapon_images/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='is_hand_to_hand_weapon',
            field=models.BooleanField(default=False, verbose_name='Ist Nahkampfwaffe'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='penetration',
            field=models.IntegerField(default=0, verbose_name='Durchschlag'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_lower',
            field=models.CharField(choices=[('-', 'Nahkampf'), ('s', 'kurz'), ('m', 'mittel'), ('l', 'lang'), ('e', 'extrem')], default='s', max_length=1, verbose_name='Untere Reichweite'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_upper',
            field=models.CharField(blank=True, choices=[('-', 'Nahkampf'), ('s', 'kurz'), ('m', 'mittel'), ('l', 'lang'), ('e', 'extrem')], max_length=1, null=True, verbose_name='Obere Reichweite'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='recoil_control',
            field=models.IntegerField(default=0, verbose_name='Rückstoßkontrolle'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='reload_actions',
            field=models.IntegerField(default=1, verbose_name='Nachladeaktionen'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.WeaponType', verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gewicht'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='wound_bonus',
            field=models.IntegerField(default=0, verbose_name='Wundenbonus'),
        ),
        migrations.AlterField(
            model_name='weaponmodification',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='modifier',
            field=models.IntegerField(default=0, verbose_name='Modifikator'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationtype',
            name='unique_equip',
            field=models.BooleanField(default=False, help_text='Eine Waffe darf nur eine Modifikation von diesem Typ haben (z.B. Visiere)', verbose_name='Einmalig ausrüsten'),
        ),
    ]
