# Generated by Django 2.0.5 on 2018-10-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0006_auto_20181010_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'item type', 'verbose_name_plural': 'item types'},
        ),
        migrations.AlterModelOptions(
            name='riotgear',
            options={'verbose_name': 'riot gear', 'verbose_name_plural': 'riot gear'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'weapon', 'verbose_name_plural': 'weapons'},
        ),
        migrations.AlterModelOptions(
            name='weaponattackmode',
            options={'verbose_name': 'attack mode', 'verbose_name_plural': 'attack modes'},
        ),
        migrations.AlterModelOptions(
            name='weaponmodification',
            options={'verbose_name': 'weapon modification', 'verbose_name_plural': 'weapon modification'},
        ),
        migrations.AlterModelOptions(
            name='weaponmodificationtype',
            options={'verbose_name': 'weapon modification type', 'verbose_name_plural': 'weapon modification type'},
        ),
        migrations.AlterModelOptions(
            name='weapontype',
            options={'verbose_name': 'weapon type', 'verbose_name_plural': 'weapon types'},
        ),
        migrations.AlterField(
            model_name='item',
            name='concealment',
            field=models.IntegerField(default=0, verbose_name='concealment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='item_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_de',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.ItemType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name_de',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='concealment',
            field=models.IntegerField(default=0, verbose_name='concealment'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='name_de',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='name_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='protection_ballistic',
            field=models.IntegerField(default=0, verbose_name='protection ballistic'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='protection_explosive',
            field=models.IntegerField(default=0, verbose_name='protection explosive'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='accuracy',
            field=models.IntegerField(default=0, verbose_name='accuracy'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='attack_modes',
            field=models.ManyToManyField(to='armory.WeaponAttackMode', verbose_name='attack modes'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='attacks_per_action',
            field=models.IntegerField(verbose_name='attacks per action'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='concealment',
            field=models.IntegerField(default=0, verbose_name='concealment'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='weapon_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='is_hand_to_hand_weapon',
            field=models.BooleanField(default=False, verbose_name='is hand to hand weapon'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name_de',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='penetration',
            field=models.IntegerField(default=0, verbose_name='penetration'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_lower',
            field=models.CharField(choices=[('-', 'hand to hand'), ('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], default='s', max_length=1, verbose_name='lower range'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_upper',
            field=models.CharField(blank=True, choices=[('-', 'hand to hand'), ('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], max_length=1, null=True, verbose_name='upper range'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='recoil_control',
            field=models.IntegerField(default=0, verbose_name='recoil control'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='reload_actions',
            field=models.IntegerField(default=1, verbose_name='reload actions'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.WeaponType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='wound_bonus',
            field=models.IntegerField(default=0, verbose_name='wound bonus'),
        ),
        migrations.AlterField(
            model_name='weaponattackmode',
            name='name_de',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weaponattackmode',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weaponmodification',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='weaponmodification',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='weaponmodification',
            name='name_de',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weaponmodification',
            name='name_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weaponmodification',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('attacks_per_action', 'attacks_per_action'), ('ammunition', 'ammunition'), ('wound_bonus', 'wound_bonus'), ('penetration', 'penetration'), ('accuracy', 'accuracy'), ('weight', 'weight'), ('recoil_control', 'recoil_control'), ('concealment', 'concealment'), ('reload_actions', 'reload_actions')], max_length=40, verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='modifier',
            field=models.IntegerField(default=0, verbose_name='modifier'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationtype',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationtype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationtype',
            name='name_de',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationtype',
            name='name_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationtype',
            name='unique_equip',
            field=models.BooleanField(default=False, help_text='A weapon may only have one modification of this type (i.E. sights)', verbose_name='unique equip'),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='name_de',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
