# Generated by Django 2.0.5 on 2018-10-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0007_auto_20181013_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='wound_bonus',
            new_name='wounds',
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('attacks_per_action', 'attacks_per_action'), ('ammunition', 'ammunition'), ('wounds', 'wounds'), ('penetration', 'penetration'), ('accuracy', 'accuracy'), ('weight', 'weight'), ('recoil_control', 'recoil_control'), ('concealment', 'concealment'), ('reload_actions', 'reload_actions')], max_length=40, verbose_name='attribute'),
        ),
    ]
