# Generated by Django 2.0.5 on 2018-10-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0008_auto_20181017_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='range_lower',
            field=models.CharField(choices=[('-', 'hand to hand - short'), ('+', 'hand to hand - long'), ('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], default='s', max_length=1, verbose_name='lower range'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_upper',
            field=models.CharField(blank=True, choices=[('-', 'hand to hand - short'), ('+', 'hand to hand - long'), ('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], max_length=1, null=True, verbose_name='upper range'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='wounds',
            field=models.IntegerField(default=0, verbose_name='wounds'),
        ),
    ]
