# Generated by Django 2.0.5 on 2018-11-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0009_auto_20181021_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='range_lower',
            field=models.CharField(choices=[('-', 'hand to hand 1m'), ('+', 'hand to hand 2m'), ('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], default='s', max_length=1, verbose_name='lower range'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range_upper',
            field=models.CharField(blank=True, choices=[('-', 'hand to hand 1m'), ('+', 'hand to hand 2m'), ('s', 'short'), ('m', 'mid'), ('l', 'long'), ('e', 'extreme')], max_length=1, null=True, verbose_name='upper range'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('attacks_per_action', 'attacks_per_action'), ('capacity', 'capacity'), ('wounds', 'wounds'), ('penetration', 'penetration'), ('accuracy', 'accuracy'), ('weight', 'weight'), ('recoil_control', 'recoil_control'), ('concealment', 'concealment'), ('reload_actions', 'reload_actions')], max_length=40, verbose_name='attribute'),
        ),
    ]
