# Generated by Django 2.0.8 on 2018-12-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0011_auto_20181210_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='riotgear',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
    ]
