# Generated by Django 2.0.13 on 2019-07-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0031_auto_20190730_0421'),
        ('armory', '0012_auto_20181210_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extensions',
            field=models.ManyToManyField(to='rules.Extension'),
        ),
        migrations.AddField(
            model_name='riotgear',
            name='extensions',
            field=models.ManyToManyField(to='rules.Extension'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='extensions',
            field=models.ManyToManyField(to='rules.Extension'),
        ),
        migrations.AddField(
            model_name='weaponmodification',
            name='extensions',
            field=models.ManyToManyField(to='rules.Extension'),
        ),
        migrations.AlterField(
            model_name='item',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rules.Extension'),
        ),
        migrations.AlterField(
            model_name='riotgear',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rules.Extension'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rules.Extension'),
        ),
        migrations.AlterField(
            model_name='weaponmodification',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rules.Extension'),
        ),
    ]
