# Generated by Django 2.0.13 on 2019-08-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0013_auto_20190730_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='riotgear',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='weaponmodification',
            name='extension',
        ),
    ]
