# Generated by Django 2.0.13 on 2019-11-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0014_auto_20190805_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('attacksperaction', 'attacks_per_action'), ('capacity', 'capacity'), ('wounds', 'wounds'), ('penetration', 'penetration'), ('accuracy', 'accuracy'), ('weight', 'weight'), ('recoilcontrol', 'recoil_control'), ('concealment', 'concealment'), ('reloadactions', 'reload_actions')], max_length=40, verbose_name='attribute'),
        ),
    ]
