# Generated by Django 2.2.14 on 2020-09-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0016_item_usable_in_combat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='range_lower',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='range_upper',
        ),
        migrations.AddField(
            model_name='weapon',
            name='range_meter',
            field=models.IntegerField(default=0, verbose_name='range (meter)'),
        ),
    ]
