# Generated by Django 2.2.14 on 2021-01-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0017_auto_20200924_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='riotgear',
            name='evasion',
            field=models.IntegerField(default=0, verbose_name='evasion'),
        ),
    ]
