# Generated by Django 2.2.18 on 2021-03-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0022_auto_20210321_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('dice_bonus', models.IntegerField(default=1, verbose_name='dice bonus')),
            ],
            options={
                'verbose_name': 'attack mode',
                'verbose_name_plural': 'attack modes',
            },
        ),
    ]
