# Generated by Django 2.2.18 on 2021-03-31 08:52

from django.db import migrations


def copy_attack_modes(apps, schema_editor):
    WeaponAttackMode = apps.get_model('armory', 'WeaponAttackMode')
    AttackMode = apps.get_model('armory', 'AttackMode')

    for wma in WeaponAttackMode.objects.all():
        AttackMode.objects.create(
            id=wma.id,
            name_de=wma.name_de,
            name_en=wma.name_en,
            dice_bonus=wma.dice_bonus)


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0023_attackmode'),
    ]

    operations = [
        migrations.RunPython(copy_attack_modes)
    ]
