# Generated by Django 2.2.18 on 2021-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0024_auto_20210331_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeaponAttackMode',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='attack_modes',
            field=models.ManyToManyField(to='armory.AttackMode', verbose_name='attack modes'),
        ),
    ]
