# Generated by Django 2.2.18 on 2021-03-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0025_auto_20210331_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponAttackMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_bonus_override', models.IntegerField(blank=True, null=True, verbose_name='dice bonus override')),
                ('attack_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.AttackMode', verbose_name='Attack Mode')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.Weapon', verbose_name='Weapon')),
            ],
            options={
                'verbose_name': 'weapon attack mode',
                'verbose_name_plural': 'weapon attack modes',
            },
        ),
    ]
