# Generated by Django 2.2.18 on 2021-03-31 09:09

from django.db import migrations


def create_weapon_attack_modes(apps, schema_editor):
    AttackMode = apps.get_model('armory', 'AttackMode')
    Weapon = apps.get_model('armory', 'Weapon')

    for w in Weapon.objects.all():
        for am in w.attack_modes.all():
            w.weaponattackmode_set.create(attack_mode=am)


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0026_weaponattackmode'),
    ]

    operations = [
        migrations.RunPython(create_weapon_attack_modes)
    ]
