# Generated by Django 2.2.18 on 2021-04-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0027_auto_20210331_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='attack_modes',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='wounds',
            field=models.IntegerField(default=0, verbose_name='bonus wounds'),
        ),
    ]
