# Generated by Django 2.2.18 on 2021-04-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0049_remove_knowledge_add_to_all_characters'),
        ('armory', '0028_auto_20210416_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponmodificationattributechange',
            name='status_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.StatusEffect', verbose_name='status effect'),
        ),
        migrations.AddField(
            model_name='weaponmodificationattributechange',
            name='status_effect_value',
            field=models.IntegerField(default=0, verbose_name='status effect value'),
        ),
        migrations.AlterField(
            model_name='weaponmodificationattributechange',
            name='attribute',
            field=models.CharField(choices=[('capacity', 'Capacity'), ('wounds', 'Bonus wounds'), ('penetration', 'Penetration'), ('concealment', 'Concealment'), ('reload_actions', 'Reload actions'), ('range_meter', 'Range (meter)')], max_length=40, verbose_name='attribute'),
        ),
    ]
