# Generated by Django 3.2.3 on 2021-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0031_auto_20210424_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackmode',
            name='capacity_consumed',
            field=models.IntegerField(default=1, verbose_name='capacity consumed'),
        ),
        migrations.AddField(
            model_name='weaponattackmode',
            name='capacity_consumed_override',
            field=models.IntegerField(blank=True, null=True, verbose_name='capacity consumed override'),
        ),
    ]
